apiVersion: apps/v1
kind: Deployment
metadata:
  name: augsburg-picks-backend
  namespace: talha-rasool-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: augsburg-picks-backend
  template:
    metadata:
      labels:
        app: augsburg-picks-backend
    spec:
      containers:
        - name: augsburg-picks-backend
          image: rasooltalha/augsburg-picks-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5001
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASS
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_DB
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
