apiVersion: v1
kind: Service
metadata:
  name: augsburg-picks-backend
spec:
  selector:
    app: augsburg-picks-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

  type: NodePort
