apiVersion: apps/v1
kind: Deployment
metadata:
  name: augsburg-picks-backend
  namespace: talha-rasool-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: augsburg-picks-backend
  template:
    metadata:
      labels:
        app: augsburg-picks-backend
    spec:
      containers:
        - name: augsburg-picks-backend
          image: rasooltalha/augsburg-picks-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5001

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGODB_URI
            - name: PORT
              value: "5001"
