apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: talha-rasool-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASS
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_DB
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PORT

          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db

      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
