apiVersion: v1
kind: Service
metadata:
  name: augsburg-picks-frontend
spec:
  selector:
    app: augsburg-picks-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort # Use NodePort for external access
